version: "3"

services:
  mysql:
    image: mysql:8.0.19
    restart: always
    ports:
      - 3306:3306
    volumes:
      - .mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: password
